/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MisVentanas;

import javax.swing.JOptionPane;

/**
 *
 * @author aitor
 */
public class V1 extends javax.swing.JFrame {

    /**
     * Creates new form V1
     */
    public V1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmModificarAb = new javax.swing.JMenuItem();
        jmAltaAb = new javax.swing.JMenuItem();
        jmBajaAb = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmModificarCl = new javax.swing.JMenuItem();
        jmAltaCl = new javax.swing.JMenuItem();
        jmBajaCl = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmModificarCa = new javax.swing.JMenuItem();
        jmAltaCa = new javax.swing.JMenuItem();
        jmBajaCa = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MisVentanas/Justicia.jpg"))); // NOI18N

        jButton1.setText("jButton1");

        jMenu2.setText("Abogado");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jmModificarAb.setText("Modificar");
        jmModificarAb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModificarAbActionPerformed(evt);
            }
        });
        jMenu2.add(jmModificarAb);

        jmAltaAb.setText("Alta");
        jmAltaAb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAltaAbActionPerformed(evt);
            }
        });
        jMenu2.add(jmAltaAb);

        jmBajaAb.setText("Baja");
        jmBajaAb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBajaAbActionPerformed(evt);
            }
        });
        jMenu2.add(jmBajaAb);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Cliente");

        jmModificarCl.setText("Modificar");
        jmModificarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModificarClActionPerformed(evt);
            }
        });
        jMenu1.add(jmModificarCl);

        jmAltaCl.setText("Alta");
        jmAltaCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAltaClActionPerformed(evt);
            }
        });
        jMenu1.add(jmAltaCl);

        jmBajaCl.setText("Baja");
        jmBajaCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBajaClActionPerformed(evt);
            }
        });
        jMenu1.add(jmBajaCl);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Caso");

        jmModificarCa.setText("Modificar");
        jmModificarCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModificarCaActionPerformed(evt);
            }
        });
        jMenu3.add(jmModificarCa);

        jmAltaCa.setText("Alta");
        jmAltaCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAltaCaActionPerformed(evt);
            }
        });
        jMenu3.add(jmAltaCa);

        jmBajaCa.setText("Baja");
        jmBajaCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBajaCaActionPerformed(evt);
            }
        });
        jMenu3.add(jmBajaCa);

        jMenuBar1.add(jMenu3);

        jMenu17.setText("SALIR");

        jMenuItem2.setText("Salir del programa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu17.add(jMenuItem2);

        jMenuBar1.add(jMenu17);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
       
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jmAltaAbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAltaAbActionPerformed
        gabinete.Gabinete.abrirAbogado("Alta");
        this.setVisible(false);
    }//GEN-LAST:event_jmAltaAbActionPerformed

    private void jmAltaClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAltaClActionPerformed
        gabinete.Gabinete.abrirCliente("Alta");
        this.setVisible(false);
    }//GEN-LAST:event_jmAltaClActionPerformed

    private void jmAltaCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAltaCaActionPerformed
        gabinete.Gabinete.abrirCaso("Alta");
        this.setVisible(false);
    }//GEN-LAST:event_jmAltaCaActionPerformed

    private void jmModificarAbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModificarAbActionPerformed
        gabinete.Gabinete.abrirAbogado("Modificar");
        this.setVisible(false);
    }//GEN-LAST:event_jmModificarAbActionPerformed

    private void jmBajaAbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBajaAbActionPerformed
        try
        {
            String cod = JOptionPane.showInputDialog(null, "Introduce el DNI del abogado que quieres borrar");
            gabinete.Gabinete.borrarAbogadoPorDni(cod);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jmBajaAbActionPerformed

    private void jmModificarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModificarClActionPerformed
        gabinete.Gabinete.abrirCliente("Modificar");
        this.setVisible(false);
    }//GEN-LAST:event_jmModificarClActionPerformed

    private void jmBajaClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBajaClActionPerformed
        try
        {
            String cod = JOptionPane.showInputDialog(null, "Introduce el DNI del cliente que quieres borrar");
            gabinete.Gabinete.borrarClientePorDni(cod);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jmBajaClActionPerformed

    private void jmModificarCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModificarCaActionPerformed
        gabinete.Gabinete.abrirCaso("Modificar");
        this.setVisible(false);
    }//GEN-LAST:event_jmModificarCaActionPerformed

    private void jmBajaCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBajaCaActionPerformed
        try
        {
            String cod = JOptionPane.showInputDialog(null, "Introduce el número de expediente del caso que quieres borrar");
            gabinete.Gabinete.borrarCasoPorNum(cod);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jmBajaCaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jmAltaAb;
    private javax.swing.JMenuItem jmAltaCa;
    private javax.swing.JMenuItem jmAltaCl;
    private javax.swing.JMenuItem jmBajaAb;
    private javax.swing.JMenuItem jmBajaCa;
    private javax.swing.JMenuItem jmBajaCl;
    private javax.swing.JMenuItem jmModificarAb;
    private javax.swing.JMenuItem jmModificarCa;
    private javax.swing.JMenuItem jmModificarCl;
    // End of variables declaration//GEN-END:variables
}
